# Generated by Django 4.2.2 on 2023-06-12 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanner",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="scanner",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
