# Generated by Django 4.2.2 on 2023-06-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0005_scanner_recognition"),
    ]

    operations = [
        migrations.DeleteModel(name="ScanHistory",),
    ]
