# Generated by Django 4.2.2 on 2023-06-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0006_delete_scanhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanner",
            name="recognition_extended",
            field=models.TextField(blank=True),
        ),
    ]
