# Generated by Django 4.2.2 on 2023-06-22 15:40

from django.db import migrations, models
import scanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_scanner_recognition_extended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='image',
            field=models.ImageField(upload_to=scanner.models.Scanner.get_image_path, verbose_name='Изображение'),
        ),
    ]
