# Generated by Django 4.2.2 on 2023-06-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_alter_scanner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanner',
            name='recognition_extended',
        ),
    ]
