# Generated by Django 4.2.2 on 2023-06-23 08:39

from django.db import migrations, models
import scanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_remove_scanner_recognition_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='English', max_length=24),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='image',
            field=models.ImageField(upload_to=scanner.models.Scanner.get_image_path, verbose_name='Image'),
        ),
    ]
