# Generated by Django 4.2.2 on 2023-06-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_scanner_lang_alter_scanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='image_denoised',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
